language: java
script: 
  - gradle clean build
  - tar -zcf hello_world_build.tar.gz build
  - ls -R
  
deploy:
  provider: releases
  api_key:
    secure: $GITPERM
  file: "README.md"
  skip_cleanup: true
  on:
    tags: false
  
